### ISSUE TITLE
Add a "read later" share.

### ISSUE THREAD

**Issue by djl** [jonschoning/espial-share-android#1]
The old [PinDroid app](https://github.com/maxpower47/PinDroid) has two share intents. One that allows adding bookmarks while editing tags, etc. and one that adds the bookmark and marks it unread without any user input.

Any chance we could get the latter implemented? It's super useful for just quickly saving URLs.

**Comment by jonschoning** [comment]
I think so but have to just have to handle authentication.  
Navigating to the add page w/ the existing behavior allows landing on the login page if not logged in.  
To just add directly without logging in I think we could utilize the new API key auth https://github.com/jonschoning/espial/pull/35 
 i think that's not to hard to add

**Comment by jonschoning** [comment]
should have something maybe next week on this

**Comment by jonschoning** [comment]
I've added this: https://github.com/jonschoning/espial-share-android/releases/tag/0.0.3
